payload:
    - "api.segment.io"
    - "app-analytics-services.com"
    - "rmonitor.qq.com"
    - "unitelogreport.reader.qq.com"
    - "otheve.beacon.qq.com"
    - "othstr.beacon.qq.com"
    - "+.jpush.cn"
    - "metrics.icloud.com"
    - "firebaselogging-pa.googleapis.com"
