export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
alias ls_pyenv_bin="ls $(pyenv prefix)/bin"
# alias python="$(pyenv which python3)"
# alias pip="$(pyenv which python3) -m pip"
# alias ipython="~/.pyenv/versions/$(cat ~/.pyenv/version)/bin/ipython"
