payload:
  - "+.bingapis.com"
  - "+.cdn.jsdelivr.net"
  - "+.microsoft-falcon.io"
  - "+.msn.com"
  - "+.microsoftapp.net"
  - "+.ipinfo.io"
  - "+.chinadigitaltimes.net"
  - "+.cloudflare-dns.com"
  - "+.godaddy.com"
  - "+.mikanani.me"
  - "+.ip-api.com"
  - "+.gitbook.com"
  - "+.sentry.io"
  - "+.ipify.org"
  - "+.tapbots.com"
  - "+.sanity.io"
  - "+.arc.net"
  - "+.segment.com"
  - "+.launchdarkly.com"
  - "+.v2ex.com"
  - "+.imgur.com"
  - "+.zeabur.com"
  - "+.brew.sh"
  - "+.moeli-desu.com"
  - "+.tampermonkey.net"
  - "+.railway.app"
  - "+.cloudinary.com"
  - "+.redditstatic.com"
  - "+.flyairport.top"
  - "+.quq.world"
  - "+.ip-api.com"
  - "+.fly.io"
  - "+.dlercloud.com"
  - "+.gravatar.com"
  - "+.bgp.he.net"
  - "+.wikimedia.org"
  - "+.wikipedia.org"
  - "+.gstatic.com"
  - "+.javdb.com"
  - "+.91porn.com"
  - "+.hysteria.network"
  - "+.nhentai.net"
  - "+.18comic.vip"
  - "+.fastly.jsdelivr.net"
  - "+.kisscos.net"
  - "+.jable.tv"
  - "+.dealmoon.co.uk"
  - "+.metacubex.one"
  - "+.jav.app"
  - "+.pythonhosted.org"
  - "+.fbcdn.net"
  - "+.linktr.ee"
  - "+.imgur.com"
  - "+.gitbook.io"
  - "+.e-hentai.org"
  - "+.gamme.com.tw"
  - "+.python-httpx.org"
  - "+.fc2.com"
  - "+.sotwe.com"
  - "+.spankbang.com"
  - "+.mastodon.online,Select"
  - "+.go-esim.com,Select"
  - "+.v2ray.com,Select"
  - "+.v2fly.org,Select"
  - "+.missav.com"
  - "+.nyaa.si"
  - "+.getchu.com"

  # 19940731.xyz
  - "telegraph.19940731.xyz"
  - "homepage.19940731.xyz"
  - "chatgpt-next-web.19940731.xyz"
  - "nextchat.19940731.xyz"
  - "obsidian-couchdb.19940731.xyz"
  - "bitwarden.19940731.xyz"
