payload:
  - 'chatgpt-next-web.19940731.xyz'
  - 'telegraph.19940731.xyz'
  - '+.bingapis.com'
  - '+.cdn.jsdelivr.net'
  - '*.microsoft-falcon.io'
  - '*.msn.com'
  - '*.microsoftapp.net'
  - '+.ipinfo.io'
  - '*.ipinfo.io'
  - '+.chinadigitaltimes.net'
  - '+.cloudflare-dns.com'
  - '+.godaddy.com'
  - '*.godaddy.com'
  - 'mikanani.me'  
  - '+.mikanani.me'
  - '+.ip-api.com'
  - 'ip-api.com'
  - '+.gitbook.com'
  - '*.gitbook.com'
