payload:
  - '+.bingapis.com'
  - '+.cdn.jsdelivr.net'
  - '*.microsoft-falcon.io'
  - '*.msn.com'
  - '*.microsoftapp.net'
  - '+.ipinfo.io'
  - '*.ipinfo.io'
  - '+.chinadigitaltimes.net'
  - '+.cloudflare-dns.com'
  - '+.godaddy.com'
  - '*.godaddy.com'
  - 'mikanani.me'  
  - '+.mikanani.me'
  - '+.ip-api.com'
  - 'ip-api.com'
  - '+.gitbook.com'
  - '*.gitbook.com'
  - '*.sentry.io'
  - '+.sentry.io'
  - '*.ipify.org'
  - '+.ipify.org'
  - '*.tapbots.com'
  - '+.tapbots.com'
  - '+.sanity.io'
  - '*.sanity.io'
  - '+.arc.net'
  - '*.arc.net'
  - '*.segment.com'
  - '+.segment.com'
  - '*.launchdarkly.com'
  - '+.launchdarkly.com'
  - '*.v2ex.com'
  - '+.v2ex.com'  
  - '*.imgur.com'
  - '+.imgur.com'
  - '*.zeabur.com'
  - '+.zeabur.com'
  - '*.brew.sh'
  - '+.brew.sh'
  - '*.moeli-desu.com'
  - '+.moeli-desu.com'
  - '*.tampermonkey.net'
  - '+.tampermonkey.net'
  - '*.railway.app'
  - '+.railway.app'
  - '*.cloudinary.com'
  - '+.cloudinary.com'  

  # 19940731.xyz
  - 'telegraph.19940731.xyz'
  - 'homepage.19940731.xyz'
  - 'chatgpt-next-web.19940731.xyz'
  - 'obsidian-couchdb.19940731.xyz'
