payload:
    - "+.wushuangai.com"
    - "+.lcdn-locator.apple.com"
    - "+.lcdn-registration.apple.com"
    - "+.argotunnel.com"
    - "+.tastientech.com"
    - "+.aihubmix.com"
    - "+.claw.buzz"
    - "+.clawcloudsingaporeprivatelimited.sjv.io"
    - "+.www.ojrq.net"
    - "+.knit.bid"

    # QQ网页端快捷登陆
    - "localhost.ptlogin2.qq.com"
    - "localhost.sec.qq.com"
