payload:
 - '+.localhost'
 - '+.wushuangai.com'
 - '+.meituan.com'
 - '+.meituan.net'
 - '+.iphone-ld.apple.com'
 - '+.lcdn-locator.apple.com'
 - '+.lcdn-registration.apple.com'
 - '+.push.apple.com'
 - '+.argotunnel.com'

 # QQ网页端快捷登陆
 - 'localhost.ptlogin2.qq.com'
 - 'localhost.sec.qq.com'
