payload:
 - '+.localhost'
 - '+.wushuangai.com'
 - '+.lcdn-locator.apple.com'
 - '+.lcdn-registration.apple.com'
 - '+.argotunnel.com'
 - 'teldrive.19940731.xyz'

 # OrbStack
 - '+.orb.local'

 # QQ网页端快捷登陆
 - 'localhost.ptlogin2.qq.com'
 - 'localhost.sec.qq.com'
